// Generated by kse.alien.PbGen from track.proto -- DO NOT EDIT.

package kse.test.alien.track


import kse.basics.{given, _}
import kse.flow.{given, _}
import kse.maths.{UInt, ULong}
import kse.alien.Pb


opaque type Mood = Int
object Mood {
  inline def apply(n: Int): Mood = n
  val MOOD_UNSPECIFIED: Mood = 0
  val HAPPY: Mood = 1
  val GLAD: Mood = 1
  val GRUMPY: Mood = 16
  extension (e: Mood) {
    inline def number: Int = e
    def name: String = e match
      case 0 => "MOOD_UNSPECIFIED"
      case 1 => "HAPPY"
      case 16 => "GRUMPY"
      case n => s"<unknown Mood $n>"
  }
}

final case class Pt(
  x: Double = 0.0,
  y: Double = 0.0,
  unknown: List[Pb.Unknown] = Nil
) extends Pb.Writable {
  def writeTo(o: Pb.Out): Unit =
    o.double(1, x)
    o.double(2, y)
    o.unknowns(unknown)
}

object Pt extends Pb.Companion[Pt] {
  val default: Pt = Pt()
  def readFrom(in: Pb.In, prior: Pt): Pt = Pb.context("Pt"):
    var x: Double = prior.x
    var y: Double = prior.y
    var unknown = prior.unknown.reverse
    while in.next() do in.field match
      case 1 => x = in.double()
      case 2 => y = in.double()
      case _ => unknown = in.keep() :: unknown
    Pt(x, y, unknown.reverse)
}

final case class Track(
  id: String = "",
  pts: Array[Pt] = Array.empty[Pt],
  tags: Map[String, Long] = Map.empty,
  score: Pb.OptFloat = Pb.OptFloat.unit,
  hops: Array[Int] = Array.empty[Int],
  extra: Track.Extra = Track.Extra.Unset,
  meta: Track.Meta Or Unit = Alt.unit,
  stamp: ULong = ULong(0L),
  payload: Mem[Byte] = Mem of Array.empty[Byte],
  wave: Mem[Double] = Mem of Array.empty[Double],
  unknown: List[Pb.Unknown] = Nil
) extends Pb.Writable {
  def writeTo(o: Pb.Out): Unit =
    o.string(1, id)
    pts.use()(v => o.msg(2, v))
    tags.foreach: (mk, mv) =>
      o.msgHeader(3, Pb.sizeString(1, mk) + Pb.sizeSInt64(2, mv))
      o.string(1, mk)
      o.sint64(2, mv)
    o.float(4, score)
    hops.use()(v => o.int32Always(5, v))
    extra match
      case Track.Extra.Note(v) => o.stringAlways(10, v)
      case Track.Extra.Anchor(v) => o.msg(11, v)
      case Track.Extra.MoodArm(v) => o.int32Always(12, v.number)
      case Track.Extra.Unset => ()
    o.msg(20, meta)
    o.uint64(21, stamp)
    o.bytes(30, payload)
    o.packedDouble(31, wave)
    o.unknowns(unknown)
  /** A copy with every decode-buffer view, recursively, replaced by owned storage. */
  def owned: Track =
    copy(
      payload = Pb.ownedBytes(payload),
      wave = Pb.ownedDoubles(wave)
    )
}

object Track extends Pb.Companion[Track] {
  enum Extra {
    case Note(value: String)
    case Anchor(value: Pt)
    case MoodArm(value: Mood)
    case Unset
  }

  final case class Meta(
    mood: Mood = Mood.MOOD_UNSPECIFIED,
    blob: Array[Byte] = Array.empty[Byte],
    unknown: List[Pb.Unknown] = Nil
  ) extends Pb.Writable {
    def writeTo(o: Pb.Out): Unit =
      o.int32(1, mood.number)
      o.bytes(2, blob)
      o.unknowns(unknown)
  }

  object Meta extends Pb.Companion[Track.Meta] {
    val default: Track.Meta = Track.Meta()
    def readFrom(in: Pb.In, prior: Track.Meta): Track.Meta = Pb.context("Meta"):
      var mood: Mood = prior.mood
      var blob: Array[Byte] = prior.blob
      var unknown = prior.unknown.reverse
      while in.next() do in.field match
        case 1 => mood = Mood(in.int32())
        case 2 => blob = in.bytes()
        case _ => unknown = in.keep() :: unknown
      Track.Meta(mood, blob, unknown.reverse)
  }

  val default: Track = Track()
  def readFrom(in: Pb.In, prior: Track): Track = Pb.context("Track"):
    var id: String = prior.id
    val pts = Pb.RefAcc(prior.pts)
    var tags: Map[String, Long] = prior.tags
    var score: Pb.OptFloat = prior.score
    val hops = Pb.IntAcc(prior.hops)
    var extra: Track.Extra = prior.extra
    var meta: Track.Meta Or Unit = prior.meta
    var stamp: ULong = prior.stamp
    var payload: Mem[Byte] = prior.payload
    var wave: Mem[Double] = prior.wave
    var unknown = prior.unknown.reverse
    while in.next() do in.field match
      case 1 => id = in.string()
      case 2 => pts += Pt.readFrom(in.sub())
      case 3 =>
        val e = in.sub()
        var mk: String = ""
        var mv: Long = 0L
        while e.next() do e.field match
          case 1 => mk = e.string()
          case 2 => mv = e.sint64()
          case _ => e.skip()
        tags = tags + (mk -> mv)
      case 4 => score = Pb.OptFloat(in.float())
      case 5 => in.int32s(hops)
      case 10 => extra = Track.Extra.Note(in.string())
      case 11 =>
        val p = extra match { case Track.Extra.Anchor(q) => q; case _ => Pt.default }
        extra = Track.Extra.Anchor(Pt.readFrom(in.sub(), p))
      case 12 => extra = Track.Extra.MoodArm(Mood(in.int32()))
      case 20 => meta = Pb.merge(in, meta, Track.Meta)
      case 21 => stamp = in.uint64()
      case 30 => payload = in.bytesView()
      case 31 => wave = in.packedDoubleView(wave)
      case _ => unknown = in.keep() :: unknown
    Track(id, pts.result, tags, score, hops.result, extra, meta, stamp, payload, wave, unknown.reverse)
}

